### ISSUE TITLE
Facilitate using Stackage curator as a library

### ISSUE THREAD

**Issue by mrkkrp** [fpco/stackage-curator#61]
Hello. I don’t know if you’ve heard of an initiative called [Stackage HEAD]( 
https://www.tweag.io/posts/2017-10-27-stackage-head.html), which aims to help catch bugs and regressions in GHC faster by periodically building a large subset of Stackage nightly with nightly GHC builds. In order to do that some manipulations on build constraints and checking of build plans are necessary. All that functionality is mostly provided by `stackage-curator`.

Manuel Chakravarty has implemented proof of concept using rather crude methods:

https://github.com/tweag/stackage-head/blob/master/PruneConstraints.hs#L9

Now I want to change the approach and use `Stackage-curator` as a library to make things nicer and more robust, however I see that the code hides much and is not handy for my task, because it’s not really written as a library. Would you accept a PR that performs some minor refactoring that would allow me complete my plan-adjusting tool in not overly horrible fashion?

**Comment by DanBurton** [comment]
We may accept such a PR, however, please also note that we are planning a larger refactor of stackage-curator to use stack. See: https://github.com/fpco/stackage/blob/new-stackage-curator/docs/stackage-curator-rewrite.md

I find it interesting that your approach is to parse `build-constraints.yaml`. You could instead use the snapshot yaml files found in https://github.com/fpco/stackage-nightly. Instead of recalculating a build plan yourself from the build constraints, you could simply read from these files, which represent specific build plans which are known to work (with the latest released version of ghc).

**Comment by mrkkrp** [comment]
Yes, but we’ll use it with not yet released GHC, e.g. currently 8.5. For start we change GHC version in build constraints file and then generate and check new plan, then prune conflicting packages.

Is GHC version specified in build constraints file used in build plan generation at all?

**Comment by mrkkrp** [comment]
As I understand it's also used evaluate parts of package description that depend on GHC version: https://github.com/fpco/stackage-curator/blob/master/Stackage/PackageDescription.hs#L59-L109.

**Comment by mrkkrp** [comment]
OK, we'll use plans from `stackage-nightly` for now. Thanks!
